-- MySQL Script generated by MySQL Workbench
-- Tue May 14 19:26:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parent` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Parent` (
  `idtable1` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lasName` VARCHAR(45) NULL,
  `child_idtable2` INT NOT NULL,
  `School_idSchool` INT NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `School`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `School` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `School` (
  `idSchool` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `manager` VARCHAR(45) NULL,
  `coach` VARCHAR(45) NULL,
  PRIMARY KEY (`idSchool`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `child` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `child` (
  `idtable2` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `sport` VARCHAR(45) NULL,
  PRIMARY KEY (`idtable2`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
